
# This is the config file for the Supabase CLI.
# This file is created by default when running `supabase init`.
# You don't need to use this if running Supabase CLI commands from a Supabase-managed project (one created by supabase/cli).
project_id = "lmevzqjaxzbvsyiswwby"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_expiry = 10080

[auth.email]
enable_confirmations = false

[functions]
[functions.get_vehicle_categories]
verify_jwt = true
[functions.get_salesperson_categories]
verify_jwt = true
[functions.assign_salesperson_category]
verify_jwt = true
[functions.remove_salesperson_category]
verify_jwt = true
[functions.get_leads]
verify_jwt = true
[functions.get_lead_messages]
verify_jwt = true
[functions.whatsapp-bot]
verify_jwt = true
