
# Reference: https://supabase.com/docs/guides/functions/quickstart#configuration
project_id = "lmevzqjaxzbvsyiswwby"

[functions.send-financing-email]
verify_jwt = false

[functions.license-plate-lookup]
verify_jwt = false
